Various Improvements
AllenInstitute/deepinterpolation_ai_internal pull request #1
Opened 2023-09-05 14:22 UTC by aamster

This PR implements various improvements.

## Logging

This PR separates logging of train and validation. By default keras will only log a single line for both training and validation, including the time taken for both together. We were having issues with very long train times, and the time was dominated by validation. We needed to separate the logging of training and validation to get insight into the long train times. 

We separate the validation time by calling `.evaluate` instead of passing validation data into `.fit`. We create custom callbacks so that `evaluate` is called after every train epoch and `ModelCheckpoint` can be used with `evaluate`. 

Manually tested. New logging looks like this:
```
2023-08-21 12:20:00 deepinterpolation.trainor_collection INFO     Epoch 1 train
Epoch 1/12
20/20 - 671s - loss: 0.9826 - 671s/epoch - 34s/step

2023-08-21 12:22:05 deepinterpolation.trainor_collection INFO     Epoch 1 validation
Epoch 1: loss improved from inf to 1.09220, saving model to /allen/aibs/informatics/aamster/di_test/1290677698_mean_squared_error-0001-1.0922.h5
83/83 - 403s - loss: 1.0922 - 403s/epoch - 5s/step

...
```

Before:
```
Epoch 2/156
20/20 [==============================] - 4376s 228s/step - loss: 0.9633 - val_loss: 0.8891
```

## Refactor

Although it did not directly fix an issue with zombie processes, I think it cleans up the code a little bit.

## Loads movie into memory in `MovieJSONGenerator`

Loads movies into memory so that we do not need to use multiprocessing to load chunks of a movies in a loop. 

Note that it looks like a different class `OphysGenerator` already did this, but we used `MovieJSONGenerator` previously, and `MovieJSONGenerator` does not subclass `OphysGenerator`.

2023-09-05 14:56 UTC, aamster commented on tests/cli/test_finetuning.py
> -def test_fine_integration_cli_ephys_finetuning(tmp_path):
removing since it was failing and we don't need the ephys code in the codebase

2023-09-06 00:24 UTC, morriscb requested changes
Refactor looks good. Much cleaner basically everywhere. Have a few questions and asks mostly related to docs and a few style issues that have carried over from the main repo.

2023-09-06 00:24 UTC, morriscb commented on deepinterpolation/generator_collection.py
> +        @param json_path:
I don't think we have agreed explicitly on a standard for documentation but I had thought most of the new docs added/modifed were numpydoc (or adjacent)?

2023-09-06 00:24 UTC, morriscb commented on deepinterpolation/cli/training.py
> -        self.logger.info("training job finished - finalizing output model")
Did our "job finished" log go somewhere else?

2023-09-06 00:24 UTC, morriscb commented on deepinterpolation/cli/fine_tuning.py
>  class FineTuning(argschema.ArgSchemaParser):
Add a quick class description doc somewhere?

2023-09-06 00:24 UTC, morriscb commented on deepinterpolation/trainor_collection.py
> +class transfer_trainer(core_trainer):
Can we change this to CamleCase for clarity now that this is our own code?

2023-09-06 00:24 UTC, morriscb commented on deepinterpolation/trainor_collection.py
>          else:
Should this be more stringent and check for a specific type/instance of self._test_data?

2023-09-06 00:24 UTC, morriscb commented on deepinterpolation/generator_collection.py
> +                    self._movs[experiment_id] = f['data'][()]
Should we parameterize "data" here and elsewhere where this HDF5 key is accessed?

2023-09-06 17:50 UTC, aamster commented on deepinterpolation/cli/fine_tuning.py
>  class FineTuning(argschema.ArgSchemaParser):
I am not adding anything in addition to what is already there

2023-09-06 17:50 UTC, aamster commented on deepinterpolation/cli/training.py
> -        self.logger.info("training job finished - finalizing output model")
moved to `run`

2023-09-06 17:50 UTC, aamster commented on deepinterpolation/generator_collection.py
> +        @param json_path:
there's no precedent in this codebase so i picked one. I will change it to numpy style

2023-09-06 17:50 UTC, aamster commented on deepinterpolation/generator_collection.py
> +                    self._movs[experiment_id] = f['data'][()]
I am not modifying the logic. It already relied on "data" being the key.

2023-09-06 17:50 UTC, aamster commented on deepinterpolation/trainor_collection.py
>          else:
I don't understand your point. It could either be a tuple or not. Actually it won't be a tuple anymore since this logic was removed. It will always be a `Sequence` type.

2023-09-06 17:50 UTC, aamster commented on deepinterpolation/trainor_collection.py
> +class transfer_trainer(core_trainer):
I am not modifying the code style beyond what I've already done. We can either completely refactor the code or write it from scratch.

2023-09-06 18:40 UTC, morriscb commented on deepinterpolation/trainor_collection.py
>          else:
Okay, would it be worth removing then?

2023-09-06 18:40 UTC, morriscb approved these changes

2023-09-06 19:14 UTC, aamster commented on deepinterpolation/trainor_collection.py
>          else:
Removed.

2023-09-06 19:23 UTC, merged