2D slicing in MovieJSONGenerator when single movie is cached
AllenInstitute/deepinterpolation_ai_internal pull request #3
Opened 2023-09-14 16:18 UTC by mikejhuang

fix bugs

2023-09-14 23:02 UTC, aamster requested changes
Could you please add a test showing that the for loop and the vectorized implementation are equivalent?

2023-09-14 23:29 UTC, mikejhuang commented
> Could you please add a test showing that the for loop and the vectorized implementation are equivalent?

The test you added that tests if the cached movie and the non-cached movie outputs are equivalent is also used to test the 2D slicing since the 2D slicing logic is only applied when the movie is cached. 

Granted, there are ways the outputs aren't equivalent that the assert checks wouldn't catch.

2023-09-14 23:42 UTC, aamster commented
I didn't see such a test. I'm looking for a test such as 
```
gen1 = MovieJSONGenerator(..., movs=...)
gen2 = MovieJSONGenerator(..., movs=None)
assert gen1[0] == gen2[0]
```

2023-09-15 16:45 UTC, aamster approved these changes

2023-09-15 16:45 UTC, aamster commented on tests/test_generator_collection.py
> +        if movs:
Can you please make this a separate test?

2023-09-18 16:07 UTC, merged